# Generated by Django 6.0 on 2025-12-11 19:59

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=subscriptions.models.default_end_date),
        ),
    ]
